FROM postgres:11.5-alpine

COPY docker/init_sql_4_meet_db.sql /docker-entrypoint-initdb.d/

COPY docker/z_entry_meet_db.sh /docker-entrypoint-initdb.d/

COPY docker/dumps/load_meet_db_dump.sql /tmp/

EXPOSE 5432