CREATE USER meet_user WITH ENCRYPTED PASSWORD '123';
ALTER ROLE meet_user WITH LOGIN;

CREATE DATABASE meet_db;
GRANT ALL PRIVILEGES ON DATABASE meet_db TO meet_user;

CREATE DATABASE meet_db_test;
GRANT ALL PRIVILEGES ON DATABASE meet_db_test TO meet_user;