# Generated by Django 2.2.7 on 2019-11-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(default='./activity/image/default_activity.jpg', max_length=127, upload_to='activity/image', verbose_name='Активность, изображение'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='image',
            field=models.ImageField(default='./event/image/default_event.jpg', max_length=127, upload_to='event/image', verbose_name='Событие, изображение'),
        ),
    ]
