# Generated by Django 2.2.7 on 2019-11-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191110_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcategory',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='./event/image/default_event.jpg', max_length=127, upload_to='event/image', verbose_name='Событие, изображение'),
        ),
    ]
